services:
  nextjs:
    build:
      context: .
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
